# Generated by Django 5.1.1 on 2024-09-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Trans')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Username', models.CharField(max_length=200)),
                ('Email', models.EmailField(default='example@django.com', max_length=200, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
