# Generated by Django 5.1.1 on 2024-09-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean_name', models.CharField(max_length=200)),
                ('dean_email', models.EmailField(default='example@django.com', max_length=200, unique=True)),
            ],
        ),
    ]
