# Generated by Django 5.1.1 on 2024-09-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dean'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_email', models.EmailField(default='example@django.com', max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.AlterModelTable(
            name='dean',
            table='Dean',
        ),
    ]
