# Generated by Django 5.1.1 on 2024-09-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teacher_alter_dean_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(default='example@django.com', max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
