# Generated by Django 5.1.1 on 2024-09-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dean'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(to='app.teacher'),
        ),
    ]
