# Generated by Django 5.1.1 on 2024-09-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_dean_student_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['teacher_name']},
        ),
    ]
