# Generated by Django 5.1.1 on 2024-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.JSONField(default='Computer Science', max_length=200, null=True),
        ),
    ]
