# Generated by Django 5.1.1 on 2024-09-25 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=200, null=True)),
                ('subject_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
            options={
                'verbose_name': 'List of Subjects',
                'db_table': 'Subject',
                'ordering': ['subject_name'],
            },
        ),
    ]
